<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNetter" Version="6.0.5" />
    <PackageReference Include="Silk.NET.Windowing" Version="2.23.0" />
    <PackageReference Include="SlangShaderSharp" Version="2026.13.1" />
    <PackageReference Include="StbImageSharp" Version="2.30.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Beryl.Common\Beryl.Common.csproj" />
    <ProjectReference Include="..\..\Beryl.Math\Beryl.Math.csproj" />
    <ProjectReference Include="..\Beryl.Input\Beryl.Input.csproj" />
    <ProjectReference Include="..\Beryl.Physics\Beryl.Physics.csproj" />
    <ProjectReference Include="..\Beryl.Scenes\Beryl.Scenes.csproj" />
    <ProjectReference Include="..\..\Beryl.RHI\Beryl.RHI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Assets\Beryl\Attributes.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Beryl\Compute.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Defaults\DummyLit.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Defaults\Sky.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Defaults\Unlit.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Beryl\Preprocessor.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Beryl\Core.slang">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Assets\Texture.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
