<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Silk.NET.OpenAL" Version="2.23.0" />
    <PackageReference Include="Silk.NET.OpenAL.Extensions.Creative" Version="2.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Beryl.Common\Beryl.Common.csproj" />
    <ProjectReference Include="..\Beryl.Physics\Beryl.Physics.csproj" />
    <ProjectReference Include="..\Beryl.Scenes\Beryl.Scenes.csproj" />
  </ItemGroup>

</Project>
