<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Beryl.Common\Beryl.Common.csproj" />
    <ProjectReference Include="..\..\Beryl.Math\Beryl.Math.csproj" />
    <ProjectReference Include="..\..\Beryl.Serialization\Beryl.Serialization.csproj" />
  </ItemGroup>

</Project>
